from typing import List, Tuple, TypedDict

def to_pascal(input: str) -> str:
    """ Really cursed converter from kebab case to pascal case """

    acc = ""

    for i in range(len(input)):
        if i == 0:
            acc += input[i].capitalize()
            continue

        if input[i - 1] == "-":
            continue

        if input[i] == "-":
            acc += input[i + 1].capitalize()
        else:
            acc += input[i]

    return acc


def gen_enum(struct_name: str, doc: str, lines: List[str]):
    def transform(line: List[str]):
        return \
            f'    #[strum(serialize = "{line[1]}")]\n'\
            f"    {to_pascal(line[1])} = {line[2].strip()},"

    return "\n".join([
        f"/// {doc}",
        "#[repr(u16)]",
        "#[derive(Clone, Copy, Eq, EnumString)]",
        '#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]',
        "#[allow(missing_docs)]",
        f"enum {struct_name} {{",
        "\n".join([transform(x.split(";")) for x in lines]),
        "}"
    ])

class Item[T](TypedDict):
    file_name: str
    src_name:  str
    enum_name: str
    doc: str

def gen_module(out_path: str, data_path: str, items: List[Item]):
    with open(f"{out_path}/mod.rs", "w") as mod:
        mod.writelines([
            "//! Autogenerated item definitions (from mimex data)\n\n",
            "\n".join([f"/// {x["doc"]}\npub mod {x["file_name"]};" for x in items])
        ])

    for i in items:
        with open(f"{out_path}/{i["file_name"]}.rs", "w") as file, \
             open(f"{data_path}/{i["src_name"]}", "r") as data:
            file.write(gen_enum(
                i["enum_name"],
                i["doc"],
                data.readlines()[1:]
            ))

if __name__ == "__main__":
    gen_module("../src/item_defs", "./data", [
        {
            "file_name": "mindustry_icon",
            "src_name":  "mimex-icons.txt",
            "enum_name": "Icon",
            "doc": "Module for mindustry icon definitions"
        },
        {
            "file_name": "mindustry_items",
            "src_name":  "mimex-items.txt",
            "enum_name": "Item",
            "doc": "Module for mindustry item definitions"
        }
    ])